### PR TITLE
Issue 445: Make leave easier to click than end room

### PR DESCRIPTION
**Pull request by manavdesai27**
# This PR is in regards to issue #445.

I have made the required changes and tested them as directed in the readme. I have used the teacher module for the testing.

## Screenshots:

Screenshot from 2021-10-11 23-37-18

### CODE REVIEW

**Comment by manavdesai27** [comment]
@triptu Can you review this PR?

**Review by triptu — APPROVED** [review]

**Comment by triptu** [comment]
@manavdesai27 looks good, thanks, merged.

**Comment by manavdesai27** [comment]
@triptu Happy to contribute!

**Comment by Deep-Codes** [comment]
Hey @manavdesai27 

Thank you for contributing to 100ms projects

Since you have contributed successfully we have something for you.

Feel free to read this blog covering ["Hacktoberfest with 100ms" ](https://www.100ms.live/blog/hacktoberfest-2021-with-100ms)

And fill [this form](https://forms.gle/8TwB48X3TqsYj5MV7) for adding information for us to ship the swags.

**Comment by manavdesai27** [comment]
@triptu This google form is asking for permission

**Comment by Deep-Codes** [comment]
> @triptu This google form is asking for permission

Let me see wait

**Comment by manavdesai27** [comment]
@Deep-Codes 
Screenshot from 2021-10-12 16-53-28

**Comment by Deep-Codes** [comment]
@manavdesai27 Check now https://forms.gle/gwo8CkkMTnuSck3w8

**Comment by manavdesai27** [comment]
@Deep-Codes works now!

**Comment by manavdesai27** [comment]
@triptu Can you please add "hacktoberfest-accepted" to this PR?

**Comment by manavdesai27** [comment]
> Hey @manavdesai27
> 
> Thank you for contributing to 100ms projects
> 
> Since you have contributed successfully we have something for you.
> 
> Feel free to read this blog covering ["Hacktoberfest with 100ms" ](https://www.100ms.live/blog/hacktoberfest-2021-with-100ms)
> 
> And fill [this form](https://forms.gle/8TwB48X3TqsYj5MV7) for adding information for us to ship the swags.

I haven't received any mail for swags. Can you please see into this?

**Comment by triptu** [comment]
> > Hey @manavdesai27
> > Thank you for contributing to 100ms projects
> > Since you have contributed successfully we have something for you.
> > Feel free to read this blog covering ["Hacktoberfest with 100ms" ](https://www.100ms.live/blog/hacktoberfest-2021-with-100ms)
> > And fill [this form](https://forms.gle/8TwB48X3TqsYj5MV7) for adding information for us to ship the swags.
> 
> I haven't received any mail for swags. Can you please see into this?

@aniketbehera

**Comment by manavdesai27** [comment]
@aniketbehera Could you please respond?

**Comment by manavdesai27** [comment]
@triptu Can you look into this?

**Pull request merged**
